[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ['py38']

[tool.pyright]
include = ["EpikCord"]
exclude = [
    "venv",
    "**/__pycache__"
]
