name: Black

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Up git
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install nox
      run: pip install nox

    - name: run Formatter
      run: |
        nox -s format
    - name: Push changes
      run: |
        git commit -m ":art: Format code automatically" -a || echo "No changes to commit"
        git push || echo "No changes to push"
