name: CI

on:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set Up git
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git pull

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: run Formatter
      run: |
        make pretty
    - name: Push changes
      run: |
        git commit -m ":art: Format code automatically" -a || echo "No changes to commit"
        git push || echo "No changes to push"

  ci:
    needs: black
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python: [ '3.8', '3.9', '3.10' ]
        os: [ ubuntu, windows, macos ]
        nox_action: ["install", "lint", "pyright"]
      fail-fast: false

    name: Nox - py ${{ matrix.python }} - ${{ matrix.os }} - ${{ matrix.nox_action }}
    steps:
      - uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: 'x64'

      - name: Update Pip
        run: pip install -U pip

      - name: Install dependencies
        run: pip install nox git+https://github.com/Bluenix2/discord-typings

      - name: Run nox
        run: nox -s ${{ matrix.nox_action }}
