name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Make Logs Directory
      run: mkdir /tmp/sphinx-log


    - name: Build HTML
      uses: ammaraskar/sphinx-action@master

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        directory: docs
        github_token: ${{ secrets.GITHUB_TOKEN }}
